name: Publish release
run-name: Publishing package to GitHub NPM Registry

on:
  push:
    branches:
      - master

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: |
          pnpm install

      - name: Set Git identity
        run: |
          git config --global user.name "Erik Isidore"
          git config --global user.email "ericssonico@proton.me"

      - run: pnpm run full-release
        env:
          NPM_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
